### ISSUE TITLE
wrong redirection when dvc push to gdrive and no verification code is shown

### ISSUE THREAD

**Issue by Min-Sheng** [iterative/dvc#8058]
# Bug Report

I have already set-up my gdrive `FOLDER_ID` accroding to the [DVC document](https://dvc.org/doc/user-guide/setup-google-drive-remote). 
However, the line for `Enter verification code:` did not show.
When I pasted the link to the browser authorized it, and click the continuing button, 
the browser redirect to `localhost:8080?code=...` and no verification code is shown.

The issue is about DVC version `2.13.0`. 
Everything looks fine after I downgraded my DVC version to `2.11.0`.

### Reproduce

1. `$ dvc add data `
2. `$ dvc remote add -d ${REMOTE_NAME} gdrive://${FOLDER_ID}`
4. `$ dvc push`

### Expected

`Enter verification code:` should be shown and the browser should redirect to the corresponding verification code.

### Environment information

DVC version `2.13.0`

**Comment by efiop** [comment]
Hey @Min-Sheng :) What error did you get? Did `dvc push` not work at all? Could you show full output of `dvc push -v`, please?

**Comment by shcheklein** [comment]
For the record, docs are a bit outdated - I've created a PR - https://github.com/iterative/dvc.org/pull/3821/files

It doesn't to `Enter verification code` now, it get's from the browser since via web server that it creates.

Do you see the `Authentication successful.`?

**Comment by Min-Sheng** [comment]
> Hey @Min-Sheng :) What error did you get? Did `dvc push` not work at all? Could you show full output of `dvc push -v`, please?

For DVC version 2.13.0
```
  0% Checking cache in '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'|                                                                                                                                               |0/? [00:00<?,    ?files/s]Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata&access_type=offline&response_type=code&approval_prompt=force

```
And it redirect to this url: http://localhost:8080/?code=4/0AdQt8qgV8SAXduPyDDgMexBuWbU61HsL8T0vFoPdS4UpGLVBnEx6-oTae10pkd7dY94fMQ&scope=https://www.googleapis.com/auth/drive%20https://www.googleapis.com/auth/drive.appdata

For DVC version 2.15.0, I got the error:
```
ERROR: unexpected error - __init__() missing 1 required positional argument: 'google_auth'
```

**Comment by shcheklein** [comment]
@Min-Sheng could you please run it with `-v` - `dvc push -v ...`

**Comment by Min-Sheng** [comment]
> @Min-Sheng could you please run it with `-v` - `dvc push -v ...`

For `2.11.0`, `dvc push -v` shows:
```
2022-07-29 06:27:39,893 DEBUG: Preparing to transfer data from '/home/vincentwu/aetherhema-contour-inferencer/.dvc/cache' to '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:27:39,893 DEBUG: Preparing to collect status from '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:27:39,893 DEBUG: Collecting status from '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:27:39,897 DEBUG: Querying 1 hashes via object_exists                                                                                                                                             
2022-07-29 06:27:40,441 DEBUG: GDrive remote auth with config '{'client_config_backend': 'settings', 'client_config_file': 'client_secrets.json', 'save_credentials': True, 'oauth_scope': ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.appdata'], 'save_credentials_backend': 'file', 'save_credentials_file': '/home/vincentwu/aetherhema-contour-inferencer/.dvc/tmp/gdrive-user-credentials.json', 'get_refresh_token': True, 'client_config': {'client_id': '710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com', 'client_secret': 'a1Fz59uTpVNeG_VGuSKDLJXv', 'auth_uri': 'https://accounts.google.com/o/oauth2/auth', 'token_uri': 'https://oauth2.googleapis.com/token', 'revoke_uri': 'https://oauth2.googleapis.com/revoke', 'redirect_uri': ''}}'.
Everything is up to date.                                                                                                                                                                                      
2022-07-29 06:27:41,757 DEBUG: Analytics is enabled.
2022-07-29 06:27:41,850 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmparjw6l81']'
2022-07-29 06:27:41,852 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmparjw6l81']'
```

For version `2.13.0`, `dvc push -v` shows:
```
2022-07-29 06:23:45,970 DEBUG: Preparing to transfer data from '/home/vincentwu/aetherhema-contour-inferencer/.dvc/cache' to '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:23:45,971 DEBUG: Preparing to collect status from '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:23:45,971 DEBUG: Collecting status from '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:23:45,983 DEBUG: Querying 1 oids via object_exists                                                                                                             
2022-07-29 06:23:46,668 DEBUG: GDrive remote auth with config '{'client_config_backend': 'settings', 'client_config_file': 'client_secrets.json', 'save_credentials': True, 'oauth_scope': ['https://www.googleapis.com/auth/drive', 'https://www.googleapis.com/auth/drive.appdata'], 'save_credentials_backend': 'file', 'save_credentials_file': '/home/vincentwu/aetherhema-contour-inferencer/.dvc/tmp/gdrive-user-credentials.json', 'get_refresh_token': True, 'client_config': {'client_id': '710796635688-iivsgbgsb6uv1fap6635dhvuei09o66c.apps.googleusercontent.com', 'client_secret': 'a1Fz59uTpVNeG_VGuSKDLJXv', 'auth_uri': 'https://accounts.google.com/o/oauth2/auth', 'token_uri': 'https://oauth2.googleapis.com/token', 'revoke_uri': 'https://oauth2.googleapis.com/revoke', 'redirect_uri': ''}}'.
Everything is up to date.                                                                                                                                                    
2022-07-29 06:23:47,892 DEBUG: Analytics is enabled.
2022-07-29 06:23:48,024 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpr4djuzj5']'
2022-07-29 06:23:48,027 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpr4djuzj5']'
```
For version `2.15.0`, `dvc push -v` shows:
```
2022-07-29 06:26:06,782 DEBUG: Preparing to transfer data from '/home/vincentwu/aetherhema-contour-inferencer/.dvc/cache' to '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:26:06,783 DEBUG: Preparing to collect status from '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:26:06,783 DEBUG: Collecting status from '1-736e5qemsLRdaGFbxiW_1pcfApwVXZH'
2022-07-29 06:26:06,787 DEBUG: Querying 1 oids via object_exists                                                                                                                                               
2022-07-29 06:26:07,229 ERROR: unexpected error - __init__() missing 1 required positional argument: 'google_auth'                                                                                             
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc/cli/__init__.py", line 185, in main
    ret = cmd.do_run()
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc/cli/command.py", line 22, in do_run
    return self.run()
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc/commands/data_sync.py", line 58, in run
    processed_files_count = self.repo.push(
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc/repo/__init__.py", line 48, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc/repo/push.py", line 68, in push
    pushed += self.cloud.push(
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc/data_cloud.py", line 109, in push
    return self.transfer(
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc/data_cloud.py", line 88, in transfer
    return transfer(src_odb, dest_odb, objs, **kwargs)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_data/transfer.py", line 158, in transfer
    status = compare_status(
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_data/status.py", line 179, in compare_status
    dest_exists, dest_missing = status(
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_data/status.py", line 151, in status
    odb.oids_exist(hashes, jobs=jobs, progress=pbar.callback)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_objects/db.py", line 319, in oids_exist
    return list(wrap_iter(remote_oids, callback))
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_objects/db.py", line 26, in wrap_iter
    for index, item in enumerate(iterable, start=1):
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_objects/db.py", line 266, in list_oids_exists
    yield from itertools.compress(oids, in_remote)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_objects/fs/base.py", line 269, in exists
    return self.fs.exists(path)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/funcy/objects.py", line 50, in __get__
    return prop.__get__(instance, type)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/funcy/objects.py", line 28, in __get__
    res = instance.__dict__[self.fget.__name__] = self.fget(instance)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/dvc_objects/fs/implementations/gdrive.py", line 106, in fs
    return _GDriveFileSystem(self._path, **self._settings)
  File "/home/vincentwu/.local/lib/python3.8/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'google_auth'
------------------------------------------------------------
2022-07-29 06:26:13,551 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2022-07-29 06:26:13,552 DEBUG: Removing '/home/vincentwu/.CT47R8eTCGpnBxKyqUckBS.tmp'
2022-07-29 06:26:13,553 DEBUG: Removing '/home/vincentwu/.CT47R8eTCGpnBxKyqUckBS.tmp'
2022-07-29 06:26:13,554 DEBUG: Removing '/home/vincentwu/.CT47R8eTCGpnBxKyqUckBS.tmp'
2022-07-29 06:26:13,555 DEBUG: Removing '/home/vincentwu/aetherhema-contour-inferencer/.dvc/cache/.oHKyjEqhnyoXXyFhJuRWzF.tmp'
2022-07-29 06:26:13,618 DEBUG: Version info for developers:
DVC version: 2.15.0 (pip)
---------------------------------
Platform: Python 3.8.10 on Linux-5.4.0-100-generic-x86_64-with-glibc2.29
Supports:
        azure (adlfs = 2022.7.0, knack = 0.9.0, azure-identity = 1.10.0),
        gdrive (pydrive2 = 1.12.1),
        gs (gcsfs = 2022.5.0),
        hdfs (fsspec = 2022.5.0, pyarrow = 8.0.0),
        webhdfs (fsspec = 2022.5.0),
        http (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        https (aiohttp = 3.8.1, aiohttp-retry = 2.5.2),
        s3 (s3fs = 2022.5.0, boto3 = 1.21.21),
        ssh (sshfs = 2022.6.0),
        oss (ossfs = 2021.8.0),
        webdav (webdav4 = 0.9.7),
        webdavs (webdav4 = 0.9.7)
Cache types: hardlink, symlink
Cache directory: nfs4 on ds1817:/volume2/AD-home
Caches: local
Remotes: gdrive
Workspace directory: nfs4 on ds1817:/volume2/AD-home
Repo: dvc, git

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2022-07-29 06:26:13,626 DEBUG: Analytics is enabled.
2022-07-29 06:26:13,830 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpy7ldeeuc']'
2022-07-29 06:26:13,833 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpy7ldeeuc']'
```

**Comment by shcheklein** [comment]
@Min-Sheng could you please try to update DVC with all the dependencies- `pip install -U "dvc[all]"` or something like this. You have an outdated (incompatible version of `pydrive2`). On our end, we should be detecting this tbh - it should be possible right cc @iterative/dvc and provide a better error message in those case. I wonder if there is a general framework for Python that just doesn't allow loading dependencies of older version.

**Comment by Min-Sheng** [comment]
I think I find the problem. It is about port forwarding! Because I run DVC on my remote server via SSH, I need to forward my localhost 8080 port to server port.

**Comment by efiop** [comment]
@Min-Sheng So it is solved for you now?

**Comment by Min-Sheng** [comment]
> @Min-Sheng So it is solved for you now?
> 
> Btw, to avoid port forwarding you might want to use a service account as noted in the docs. https://dvc.org/doc/user-guide/setup-google-drive-remote#setup-a-google-drive-dvc-remote
@efiop Yes, I solved it with port forwarding.

**Comment by xihajun** [comment]
Thanks for all of this. May I kindly ask if we went back to version `2.11.0`, will we still have the same issue?

**Comment by shakraz** [comment]
hey! any update? still having same issue with dvc 2.38.1 (pydrive2-1.15.0).

**Comment by efiop** [comment]
@xihajun Sorry for a late response. As long as you update dvc along with corresponding `pydrive2` version (e.g. make sure pip check is not complaining) - it should work fine.

@shakraz Please share more details about the error you are getting. There has been multiple things discussed in this ticket with different workaround solutions.

**Comment by shakraz** [comment]
@efiop , thank you for quick responce. The error is exactly the same as mentioned @Min-Sheng 
After `dvc push`  and granting neccessary permissions to DVC and clicking the continuing button,
the browser redirect to localhost:8080?code=... and no `Authentication successful.` is shown.

**Comment by efiop** [comment]
@shakraz Anything weird about your setup? VPN, proxies or something else?

**Comment by Netherwulf** [comment]
I am having the same issue as @shakraz, when I try to use DVC commands related to the Google Drive on my ssh server. It is behind the openvpn VPN and I assume, that this may cause this issue.

**Comment by xihajun** [comment]
> `ssh -L 8080:localhost:8080 your-username@your-remote-name`

Great script to solve the issue (but for things inside an internal network, it may still be an issue)
