### ISSUE TITLE
pull: produces empty directory

### ISSUE THREAD

**Issue by td-anne** [iterative/dvc#9651]
# Bug Report

## Description

I have DVC set up with S3 remotes, probably misconfigured. When I do `dvc pull` it creates empty directories for the data and claims to have succeeded even though the `file.dvc` file lists many files taking up much space. Subsequent use of `dvc pull` claims everything is up to date.

### Reproduce

1. Clone the git repository of a project successfully using dvc
2. `dvc add remote s3://something-i-probably-dont-have-access-to`
3. `dvc pull`
4. Confirm that no data has been obtained and no error message has been emitted.

### Expected

Either data is downloaded from the remote or an error message is emitted.

The size, number of files, and md5sum in the `.dvc` file match what is present after a `dvc pull`. Mismatches lead to error messages with commands like `dvc pull` and `dvc update`. 

### Environment information

**Output of `dvc doctor`:**

```console
$ dvc doctor
DVC version: 3.1.0 (pip)
------------------------
Platform: Python 3.8.10 on Linux-5.4.0-147-generic-x86_64-with-glibc2.29
Subprojects:
	dvc_data = 2.0.2
	dvc_objects = 0.23.0
	dvc_render = 0.5.3
	dvc_task = 0.3.0
	scmrepo = 1.0.4
Supports:
	http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
	s3 (s3fs = 2023.6.0, boto3 = 1.26.76)
Config:
	Global: /home/anne/.config/dvc
	System: /etc/xdg/dvc
Cache types: <https://error.dvc.org/no-dvc-cache>
Caches: local
Remotes: s3, s3
Workspace directory: ext4 on /dev/mapper/ubuntu--vg-ubuntu--lv
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/af052bc392ee89f0efbc7a8ac0aa350b
```

**Additional Information (if any):**

```console
$ dvc pull --verobse
2023-06-22 13:59:55,569 DEBUG: v3.1.0 (pip), CPython 3.8.10 on Linux-5.4.0-147-generic-x86_64-with-glibc2.29
2023-06-22 13:59:55,569 DEBUG: command: /home/anne/.cache/pypoetry/virtualenvs/explore-dvc-lhhzaVKj-py3.8/bin/dvc pull --verbose
Everything is up to date.                                                                                                         
2023-06-22 13:59:55,803 DEBUG: Analytics is enabled.
2023-06-22 13:59:55,827 DEBUG: Trying to spawn '['daemon', '-q', 'analytics', '/tmp/tmpqg__r3dm']'
2023-06-22 13:59:55,828 DEBUG: Spawned '['daemon', '-q', 'analytics', '/tmp/tmpqg__r3dm']'
```

**Comment by pmrowla** [comment]
discord context: https://discord.com/channels/485586884165107732/1121441414115495996

**Comment by dberenbaum** [comment]
Sounds similar to #9482

**Comment by efiop** [comment]
or might be actually related to #9618 @td-anne Could you try installing dvc from the upstream?  E.g.

`pip install git+https://github.com/iterative/dvc`

I think that problem should be fixed for you there.

**Comment by td-anne** [comment]
The version in git as of now (version number 3.2.1 but pulled from git as above) still does not report an error and does not actually create the files specified in the `.dvc` files, which call for thousands of files to exist.
```console
% dvc pull
A       datasets/base/                                                          
A       models/base/
2 files added
```

**Comment by efiop** [comment]
@td-anne Please show `dvc list . datasets/base --recursive`, I have a suspicion that those dirs are currently recorded as empty.

**Comment by td-anne** [comment]
The command executes with no output. I'm not quite sure what it is supposed to do, but `dvc status` immediately after `dvc pull` reports that the directories have changed down to being empty. (They are indeed empty after running `dvc pull` in DVC 3.) `dvc add` in this context updates the `.dvc` files to confirm that they should be empty.

**Comment by efiop** [comment]
@td-anne In a clean repo, without `dvc add`ing empty dirs, that ls command still shows no output?

**Comment by td-anne** [comment]
Yes, in a clean repo I get no output at all.

**Comment by constantdcx** [comment]
Hello, I have the same issue. 

I used to always pull the same dataset with `dvc pull` but since I upgraded to 3.2.2, it only pulls an empty folder.
I last updated and pushed my dataset using version < 3.0.0 a few weeks ago.

Here is the output of `dvc pull` after deleting the dataset folder:

```
$ dvc pull
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files: 
md5-dos2unix: 969267e660081b59e42d22c2ab4f8960.dir
A       dataset/
1 file added
```

And if I `dvc pull` once more:
```
$ dvc pull
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                                                          
md5-dos2unix: 969267e660081b59e42d22c2ab4f8960.dir
Everything is up to date.  
```

**Comment by efiop** [comment]
@constantdcx Could you try downgrading to <3 and see if that helps?

**Comment by constantdcx** [comment]
Hello @efiop, thank you for your answer.
I removed the version installed with snap `sudo snap remove dvc` and installed an older dvc version with apt `sudo apt install dvc=2.48.0`.

This is the new result of `dvc pull`:
```
$ dvc pull
WARNING: Some of the cache files do not exist neither locally nor on remote. Missing cache files:                                                                                                          
name: None, md5: 969267e660081b59e42d22c2ab4f8960.dir
WARNING: No file hash info found for '/home/constantin/dataset'. It won't be created.                                                                                             
1 file failed                                                                                                                                                                                              
ERROR: failed to pull data from the cloud - Checkout failed for following targets:
/home/constantin/dataset
Is your cache up to date?
<https://error.dvc.org/missing-files>
```

I get the same result with other dvc versions 2.*. Is there a specific version I should try ?

**Comment by constantdcx** [comment]
Hello, the issue was actually on my side, someone had added a new version of the dataset with `dvc add dataset` without pushing it with dvc and committed these changes with git.
I reverted to an old version of the 'dataset.dvc' and everything works with both dvc < 3 and dvc > 3.

Thank you very much for your help.

**Comment by efiop** [comment]
@constantdcx Glad to hear it works.

@td-anne I'm not able to reproduce so far. One possible solution might be that some entries in our internal cache got corrupted. Try `rm -rf /var/tmp/dvc`, maybe that should help.

**Comment by dberenbaum** [comment]
Reproduction script:

```bash
rm -rf /Library/Caches/dvc/repo/63a86d1aa938a14ed3f3014e34dbe38a
rm -rf example-get-started-http-private-fixture
git clone git@github.com:iterative/example-get-started-http-private-fixture.git
cd example-get-started-http-private-fixture
dvc pull
dvc remote modify private-http auth basic
dvc remote modify private-http user user1
dvc remote modify private-http password password1
dvc pull
rm -rf /Library/Caches/dvc/repo/63a86d1aa938a14ed3f3014e34dbe38a
dvc pull
```

The 1st pull fails and creates empty directories. The 2nd pull fails even though it should work. The 3rd pull succeeds after deleting the site cache dir.

**Comment by dberenbaum** [comment]
Hoping this solves #9653 and #9730 but consolidating here for now since there's a reproduction script. @iterative/dvc If anyone has time, this looks to be a different issue than #9785.

**Comment by dberenbaum** [comment]
The original issue may be the same as #9785 but the repro script does not run into the same empty directories problem.

First I run without setting the auth correctly:

```bash
rm -rf /Library/Caches/dvc/repo/63a86d1aa938a14ed3f3014e34dbe38a
rm -rf example-get-started-http-private-fixture
git clone git@github.com:iterative/example-get-started-http-private-fixture.git
cd example-get-started-http-private-fixture
dvc pull
```

After this, only the `data.xml` file is found in the cache:

```bash
$ tree .dvc/cache/
.dvc/cache/
└── files
    └── md5
        └── 22
            └── a1a2931c8370d3aeedd7183606fd7f
```

Then I fix the auth issues and pull again:

```bash
dvc remote modify private-http auth basic
dvc remote modify private-http user user1
dvc remote modify private-http password password1
dvc pull
```

I get the expected non-empty `.dir` files, but the files referenced by them don't get fetched:

```bash
$ tree .dvc/cache/
.dvc/cache/
└── files
    └── md5
        ├── 15
        │   └── 3aad06d376b6595932470e459ef42a.dir
        ├── 22
        │   └── a1a2931c8370d3aeedd7183606fd7f
        ├── 25
        │   └── 79477b2696940f13279bef61dbeae0
        ├── 4c
        │   └── f269097d9561fa2116b57665a86928.dir
        ├── 51
        │   └── 199e7a6ab977cb92c39b84306c1389
        ├── de
        │   └── 2b079fb50429294048e1ca64fa59bf.dir
        ├── e4
        │   └── 7047573188bfc2079ea080ead80520
        └── f3
            └── 5d4cc2c552ac959ae602162b8543f3.dir

10 directories, 8 files

$ cat .dvc/cache/files/md5/15/3aad06d376b6595932470e459ef42a.dir
[{"md5": "b656f1a8273d0c541340cb129fd5d5a9", "relpath": "test.tsv"}, {"md5": "9ca281786366acca17632c27c5c5cc75", "relpath": "train.tsv"}]%
```

**Comment by dberenbaum** [comment]
The issue looks to be coming from:

https://github.com/iterative/dvc/blob/761422638fe3a16dd0fd42792cfc121becb0010e/dvc/repo/fetch.py#L130-L136

AFAICT `dvc_data.index.fetch.collect` is collecting the keys from the index. When there is no existing index (like if you drop the site cache dir), `collect` expands to get all the expected keys. When there was a previously failed pull, the index already contains the dir keys but none of keys for the contents inside the dir, and `collect` only returns the directory itself with none of its subpaths.

**Comment by efiop** [comment]
With https://github.com/iterative/dvc/pull/9800: 

```
dvc-3.11.2-debug) ➜  example-get-started-http-private-fixture git:(main) dvc pull
ERROR: unexpected error - failed to load directory ('data', 'prepared'): http://35.194.53.251/files/md5/15/3aad06d376b6595932470e459ef42a.dir: 401, message='Unauthorized', url=URL('http://35.194.53.251/files/md5/15/3aad06d376b6595932470e459ef42a.dir')

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
```

so it was indeed the same problem as in linked issues as noticed and pointed out by @dberenbaum 🙏
